name: Sync to GitLab

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Sync to GitLab
      run: |
        git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/david.hospinal/portfolio-simulator-sync.git
        git push gitlab --all --force
        git push gitlab --tags --force
